#!/usr/bin/env bash
# Print 10 times Best School with While Loop
# but for the 9th iteration, displays Holberton School and then Hi

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]
    then
	echo "Hi"
    fi

    ((i++))
done
